env:
 - CABALVER=1.20 GHCVER=7.8.4
 #- CABALVER=1.22 GHCVER=7.10.1 # bytestring-trie not yet fixed
 #- CABALVER=head GHCVER=head   # see section about GHC HEAD snapshots

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

script:
 - cabal install --run-tests ./ide-backend ./ide-backend-rts ./ide-backend-server ./ide-backend-common
