matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.1 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.1
  - env: GHCVER=7.10.2 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
  - env: GHCVER=head STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-head
  allow_failures:
    - env: GHCVER=head STACK_YAML=stack.yaml

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - ./travis_long stack --no-terminal --skip-ghc-check build ide-backend-server
  - ./travis_long stack --no-terminal --skip-ghc-check test
